export const All = 'All';
export const Central = 'Central';
export const South = 'South';
export const East = 'East';
export const North = 'North';
export const Northeast = 'Northeast';
export const Western = 'Western';
export const Unknown = 'Unknown';

export const region = {
  All: 'ทั้งหมด',
  Central: 'ภาคกลาง',
  North: 'ภาคเหนือ',
  South: 'ภาคใต้',
  East: 'ภาคตะวันออก',
  Western: 'ภาคตะวันตก',
  Northeast: 'ภาคอีสาน',
  Unknown: 'ไม่ระบุ',
};

export const provinceThai = {
  Unknown: { name: 'ไม่พบข้อมูล', zone: Unknown },
  Bangkok: { name: 'กรุงเทพมหานคร', zone: Central },
  Nonthaburi: { name: 'นนทบุรี', zone: Central },
  Phuket: { name: 'ภูเก็ต', zone: South },
  'Samut Prakan': { name: 'สมุทรปราการ', zone: Central },
  Chonburi: { name: 'ชลบุรี', zone: East },
  Yala: { name: 'ยะลา', zone: South },
  Pattani: { name: 'ปัตตานี', zone: South },
  Songkhla: { name: 'สงขลา', zone: South },
  'Chiang Mai': { name: 'เชียงใหม่', zone: North },
  'Pathum Thani': { name: 'ปทุมธานี', zone: Central },
  Narathiwat: { name: 'นราธิวาส', zone: South },
  'Nakhon Pathom': { name: 'นครปฐม', zone: Central },
  'Nakhon Ratchasima': { name: 'นครราชสีมา', zone: Northeast },
  'Samut Sakhon': { name: 'สมุทรสาคร', zone: Central },
  'Prachuap Khiri Khan': { name: 'ประจวบคีรีขันธ์', zone: Western },
  'Ubon Ratchathani': { name: 'อุบลราชธานี', zone: Northeast },
  'Surat Thani': { name: 'สุราษฎร์ธานี', zone: South },
  Krabi: { name: 'กระบี่', zone: South },
  Chachoengsao: { name: 'ฉะเชิงเทรา', zone: East },
  'Sa Kaeo': { name: 'สระแก้ว', zone: East },
  Buriram: { name: 'บุรีรัมย์', zone: Northeast },
  Kanchanaburi: { name: 'กาญจนบุรี', zone: Western },
  'Chiang Rai': { name: 'เชียงราย', zone: North },
  Surin: { name: 'สุรินทร์', zone: Northeast },
  Phatthalung: { name: 'พัทลุง', zone: South },
  'Udon Thani': { name: 'อุดรธานี', zone: Northeast },
  Ratchaburi: { name: 'ราชบุรี', zone: Western },
  Sisaket: { name: 'ศรีสะเกษ', zone: Northeast },
  'Nakhon Sawan': { name: 'นครสวรรค์', zone: Central },
  'Nakhon Si Thammarat': { name: 'นครศรีธรรมราช', zone: South },
  Trang: { name: 'ตรัง', zone: South },
  Saraburi: { name: 'สระบุรี', zone: Central },
  'Mae Hong Son': { name: 'แม่ฮ่องสอน', zone: North },
  'Suphan Buri': { name: 'สุพรรณบุรี', zone: Central },
  Mukdahan: { name: 'มุกดาหาร', zone: Northeast },
  'Khon Kaen': { name: 'ขอนแก่น', zone: Northeast },
  Phitsanulok: { name: 'พิษณุโลก', zone: Central },
  Prachinburi: { name: 'ปราจีนบุรี', zone: East },
  Rayong: { name: 'ระยอง', zone: East },
  'Nong Bua Lamphu': { name: 'หนองบัวลำภู', zone: Northeast },
  Lamphun: { name: 'ลำพูน', zone: North },
  Lampang: { name: 'ลำปาง', zone: North },
  Chanthaburi: { name: 'จันทบุรี', zone: East },
  Phetchabun: { name: 'เพชรบูรณ์', zone: Central },
  Sukhothai: { name: 'สุโขทัย', zone: Central },
  Kalasin: { name: 'กาฬสินธุ์', zone: Northeast },
  'Roi Et': { name: 'ร้อยเอ็ด', zone: Northeast },
  'Nong Khai': { name: 'หนองคาย', zone: Northeast },
  Uttaradit: { name: 'อุตรดิตถ์', zone: North },
  Tak: { name: 'ตาก', zone: Western },
  Phayao: { name: 'พะเยา', zone: North },
  Chaiyaphum: { name: 'ชัยภูมิ', zone: Northeast },
  'Nakhon Nayok': { name: 'นครนายก', zone: Central },
  Lopburi: { name: 'ลพบุรี', zone: Central },
  'Amnat Charoen': { name: 'อำนาจเจริญ', zone: Northeast },
  'Phra Nakhon Si Ayutthaya': { name: 'พระนครศรีอยุธยา', zone: Central },
  Loei: { name: 'เลย', zone: Northeast },
  'Sakon Nakhon': { name: 'สกลนคร', zone: Northeast },
  'Samut Songkhram': { name: 'สมุทรสงคราม', zone: Central },
  Chumphon: { name: 'ชุมพร', zone: South },
  Yasothon: { name: 'ยโสธร', zone: Northeast },
  Phrae: { name: 'แพร่', zone: North },
  'Maha Sarakham': { name: 'มหาสารคาม', zone: Northeast },
  Phetchaburi: { name: 'เพชรบุรี', zone: Western },
  'Nakhon Phanom': { name: 'นครพนม', zone: Northeast },
  'Uthai Thani': { name: 'อุทัยธานี', zone: Central },
  Nan: { name: 'น่าน', zone: North },
  'Phang Nga': { name: 'พังงา', zone: South },
  Ranong: { name: 'ระนอง', zone: South },
  Satun: { name: 'สตูล', zone: South },
  Trat: { name: 'ตราด', zone: East },
  'Bueng Kan': { name: 'บึงกาฬ', zone: Northeast },
  'Kamphaeng Phet': { name: 'กำแพงเพชร', zone: Central },
  'Chai Nat': { name: 'ชัยนาท', zone: Central },
  Phichit: { name: 'พิจิตร', zone: Central },
  'Sing Buri': { name: 'สิงห์บุรี', zone: Central },
  'Ang Thong': { name: 'อ่างทอง', zone: Central },
};
